<?php

namespace App\Http\Controllers;

use App\Models\WebsiteReportSnapshot;
use App\Services\Reports\ClientReportService;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * One-click Google disavow export: the toxic referring domains flagged by
 * BacklinkToxicityScorer, in the exact `domain:` format Google's Disavow
 * Links tool accepts. Read-only over the cached snapshot — never triggers a
 * generation. Authed like the report view (any signed-in viewer of the
 * report can export; the file contains no private data — it lists the same
 * domains the report already shows).
 */
class ReportDisavowController extends Controller
{
    public function __invoke(Request $request): Response
    {
        $domain = WebsiteReportSnapshot::normalizeDomain((string) $request->query('url', ''));
        abort_if($domain === '', 404);

        $snapshot = WebsiteReportSnapshot::forDomain($domain, (bool) $request->user()?->is_admin);
        abort_if($snapshot === null || $snapshot->status !== 'ready' || empty($snapshot->payload), 404);

        $payload = app(ClientReportService::class)->withTraffic($snapshot->payload, null);
        $toxic = array_values(array_filter(array_map(
            fn ($d) => strtolower(trim((string) $d)),
            (array) ($payload['link_risk']['toxic_domains'] ?? []),
        )));
        abort_if($toxic === [], 404);

        sort($toxic);
        $lines = array_merge([
            '# Disavow file for '.$domain,
            '# Generated by Serfix on '.now()->toDateString(),
            '# '.count($toxic).' domains flagged as toxic (link networks, link-selling sources, spam).',
            '# Review this list before uploading to Google Search Console → Disavow links.',
            '',
        ], array_map(fn ($d) => 'domain:'.preg_replace('/^www\./', '', $d), $toxic));

        return response(implode("\n", $lines)."\n", 200, [
            'Content-Type' => 'text/plain; charset=UTF-8',
            'Content-Disposition' => 'attachment; filename="disavow-'.$domain.'-'.now()->format('Ymd').'.txt"',
        ]);
    }
}
